name: ramadan_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  adaptive_theme:
  flutter_screenutil:
  fluttertoast: 
  go_router: 
  flutter_bloc:
  logger:
  url_launcher:
  skeletonizer:
  persistent_bottom_nav_bar:
  equatable:
  intl: 
  connectivity_plus:
  geolocator: 
  geocoding:
  dio:  
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  flutter_native_splash:
  # awesome_notifications:
  permission_handler: 
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter:

 
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400      

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700

